### ISSUE TITLE
Los bloques de codigo rompen el layout en mobile.

### ISSUE THREAD

**Issue by elstron** [SofiDevO/sofi-blog#2]
Los bloques de codigo rompen el layout especialmente en donde se usan enlaces largos como este:

![image](https://github.com/user-attachments/assets/69b3162c-e600-425e-8a6b-d453db2d6016)

![image](https://github.com/user-attachments/assets/f07ed123-60a4-4515-8614-380719fde82f)

**Comment by SofiDevO** [comment]
Apenas agregue algunosestilos pero al blog le falta mucho todavía
